//https://theremin.music.uiowa.edu/MISpiano.html

function pianoTunes()
{
    globalThis.a1 = new Audio("./tunes/piano/A1_piano.wav")
    globalThis.b1 = new Audio("./tunes/piano/B1_piano.wav")
    globalThis.c1 = new Audio("./tunes/piano/C1_piano.wav")
    globalThis.d1 = new Audio("./tunes/piano/D1_piano.wav")
    globalThis.e1 = new Audio("./tunes/piano/E1_piano.wav")
    globalThis.f1 = new Audio("./tunes/piano/F1_piano.wav")
    globalThis.g1 = new Audio("./tunes/piano/G1_piano.wav")
    globalThis.as1 = new Audio("./tunes/piano/As1_piano.wav")
    globalThis.bs1 = new Audio("./tunes/piano/Bs1_piano.wav")
    globalThis.cs1 = new Audio("./tunes/piano/Cs1_piano.wav")
    globalThis.ds1 = new Audio("./tunes/piano/Ds1_piano.wav")
    globalThis.es1 = new Audio("./tunes/piano/Es1_piano.wav")
    globalThis.fs1 = new Audio("./tunes/piano/Fs1_piano.wav")
    globalThis.gs1 = new Audio("./tunes/piano/Gs1_piano.wav")
    globalThis.a2 = new Audio("./tunes/piano/A2_piano.wav")
    globalThis.b2 = new Audio("./tunes/piano/B2_piano.wav")
    globalThis.c2 = new Audio("./tunes/piano/C2_piano.wav")
    globalThis.d2 = new Audio("./tunes/piano/D2_piano.wav")
    globalThis.e2 = new Audio("./tunes/piano/E2_piano.wav")
    globalThis.f2 = new Audio("./tunes/piano/F2_piano.wav")
    globalThis.g2 = new Audio("./tunes/piano/G2_piano.wav")
    globalThis.as2 = new Audio("./tunes/piano/As2_piano.wav")
    globalThis.bs2 = new Audio("./tunes/piano/Bs2_piano.wav")
    globalThis.cs2 = new Audio("./tunes/piano/Cs2_piano.wav")
    globalThis.ds2 = new Audio("./tunes/piano/Ds2_piano.wav")
    globalThis.es2 = new Audio("./tunes/piano/Es2_piano.wav")
    globalThis.fs2 = new Audio("./tunes/piano/Fs2_piano.wav")
    globalThis.gs2 = new Audio("./tunes/piano/Gs2_piano.wav")
    globalThis.a3 = new Audio("./tunes/piano/A3_piano.wav")
    globalThis.b3 = new Audio("./tunes/piano/B3_piano.wav")
    globalThis.c3 = new Audio("./tunes/piano/C3_piano.wav")
    globalThis.d3 = new Audio("./tunes/piano/D3_piano.wav")
    globalThis.e3 = new Audio("./tunes/piano/E3_piano.wav")
    globalThis.f3 = new Audio("./tunes/piano/F3_piano.wav")
    globalThis.g3 = new Audio("./tunes/piano/G3_piano.wav")
    globalThis.as3 = new Audio("./tunes/piano/As3_piano.wav")
    globalThis.bs3 = new Audio("./tunes/piano/Bs3_piano.wav")
    globalThis.cs3 = new Audio("./tunes/piano/Cs3_piano.wav")
    globalThis.ds3 = new Audio("./tunes/piano/Ds3_piano.wav")
    globalThis.es3 = new Audio("./tunes/piano/Es3_piano.wav")
    globalThis.fs3 = new Audio("./tunes/piano/Fs3_piano.wav")
    globalThis.gs3 = new Audio("./tunes/piano/Gs3_piano.wav")
    globalThis.a4 = new Audio("./tunes/piano/A4_piano.wav")
    globalThis.b4 = new Audio("./tunes/piano/B4_piano.wav")
    globalThis.c4 = new Audio("./tunes/piano/C4_piano.wav")
    globalThis.d4 = new Audio("./tunes/piano/D4_piano.wav")
    globalThis.e4 = new Audio("./tunes/piano/E4_piano.wav")
    globalThis.f4 = new Audio("./tunes/piano/F4_piano.wav")
    globalThis.g4 = new Audio("./tunes/piano/G4_piano.wav")
    globalThis.as4 = new Audio("./tunes/piano/As4_piano.wav")
    globalThis.bs4 = new Audio("./tunes/piano/Bs4_piano.wav")
    globalThis.cs4 = new Audio("./tunes/piano/Cs4_piano.wav")
    globalThis.ds4 = new Audio("./tunes/piano/Ds4_piano.wav")
    globalThis.es4 = new Audio("./tunes/piano/Es4_piano.wav")
    globalThis.fs4 = new Audio("./tunes/piano/Fs4_piano.wav")
    globalThis.gs4 = new Audio("./tunes/piano/Gs4_piano.wav")
    globalThis.a5 = new Audio("./tunes/piano/A5_piano.wav")
    globalThis.b5 = new Audio("./tunes/piano/B5_piano.wav")
    globalThis.c5 = new Audio("./tunes/piano/C5_piano.wav")
    globalThis.d5 = new Audio("./tunes/piano/D5_piano.wav")
    globalThis.e5 = new Audio("./tunes/piano/E5_piano.wav")
    globalThis.f5 = new Audio("./tunes/piano/F5_piano.wav")
    globalThis.g5 = new Audio("./tunes/piano/G5_piano.wav")
    globalThis.as5 = new Audio("./tunes/piano/As5_piano.wav")
    globalThis.bs5 = new Audio("./tunes/piano/Bs5_piano.wav")
    globalThis.cs5 = new Audio("./tunes/piano/Cs5_piano.wav")
    globalThis.ds5 = new Audio("./tunes/piano/Ds5_piano.wav")
    globalThis.es5 = new Audio("./tunes/piano/Es5_piano.wav")
    globalThis.fs5 = new Audio("./tunes/piano/Fs5_piano.wav")
    globalThis.gs5 = new Audio("./tunes/piano/Gs5_piano.wav")
    globalThis.a6 = new Audio("./tunes/piano/A6_piano.wav")
    globalThis.b6 = new Audio("./tunes/piano/B6_piano.wav")
    globalThis.c6 = new Audio("./tunes/piano/C6_piano.wav")
    globalThis.d6 = new Audio("./tunes/piano/D6_piano.wav")
    globalThis.e6 = new Audio("./tunes/piano/E6_piano.wav")
    globalThis.f6 = new Audio("./tunes/piano/F6_piano.wav")
    globalThis.g6 = new Audio("./tunes/piano/G6_piano.wav")
    globalThis.as6 = new Audio("./tunes/piano/As6_piano.wav")
    globalThis.bs6 = new Audio("./tunes/piano/Bs6_piano.wav")
    globalThis.cs6 = new Audio("./tunes/piano/Cs6_piano.wav")
    globalThis.ds6 = new Audio("./tunes/piano/Ds6_piano.wav")
    globalThis.es6 = new Audio("./tunes/piano/Es6_piano.wav")
    globalThis.fs6 = new Audio("./tunes/piano/Fs6_piano.wav")
    globalThis.gs6 = new Audio("./tunes/piano/Gs6_piano.wav")
    globalThis.a7 = new Audio("./tunes/piano/A7_piano.wav")
    globalThis.b7 = new Audio("./tunes/piano/B7_piano.wav")
    globalThis.c7 = new Audio("./tunes/piano/C7_piano.wav")
    globalThis.d7 = new Audio("./tunes/piano/D7_piano.wav")
    globalThis.e7 = new Audio("./tunes/piano/E7_piano.wav")
    globalThis.f7 = new Audio("./tunes/piano/F7_piano.wav")
    globalThis.g7 = new Audio("./tunes/piano/G7_piano.wav")
    globalThis.as7 = new Audio("./tunes/piano/As7_piano.wav")
    globalThis.bs7 = new Audio("./tunes/piano/Bs7_piano.wav")
    globalThis.cs7 = new Audio("./tunes/piano/Cs7_piano.wav")
    globalThis.ds7 = new Audio("./tunes/piano/Ds7_piano.wav")
    globalThis.es7 = new Audio("./tunes/piano/Es7_piano.wav")
    globalThis.fs7 = new Audio("./tunes/piano/Fs7_piano.wav")
    globalThis.gs7 = new Audio("./tunes/piano/Gs7_piano.wav")

}

pianoTunes()

export const tuneOptions = 
[
    {name: "a1", value: a1},
    {name: "b1", value: b1},
    {name: "c1", value: c1}, 
    {name: "d1", value: d1},
    {name: "e1", value: e1}, 
    {name: "f1", value: f1},
    {name: "g1", value: g1}, 
    {name: "as1", value: as1},
    {name: "bs1", value: bs1},
    {name: "cs1", value: cs1}, 
    {name: "ds1", value: ds1},
    {name: "es1", value: es1}, 
    {name: "fs1", value: fs1},
    {name: "gs1", value: gs1},
    {name: "a2", value: a2},
    {name: "b2", value: b2},
    {name: "c2", value: c2}, 
    {name: "d2", value: d2},
    {name: "e2", value: e2}, 
    {name: "f2", value: f2},
    {name: "g2", value: g2}, 
    {name: "as2", value: as2},
    {name: "bs2", value: bs2},
    {name: "cs2", value: cs2}, 
    {name: "ds2", value: ds2},
    {name: "es2", value: es2}, 
    {name: "fs2", value: fs2},
    {name: "gs2", value: gs2},
    {name: "a3", value: a3},
    {name: "b3", value: b3},
    {name: "c3", value: c3}, 
    {name: "d3", value: d3},
    {name: "e3", value: e3}, 
    {name: "f3", value: f3},
    {name: "g3", value: g3}, 
    {name: "as3", value: as3},
    {name: "bs3", value: bs3},
    {name: "cs3", value: cs3}, 
    {name: "ds3", value: ds3},
    {name: "es3", value: es3}, 
    {name: "fs3", value: fs3},
    {name: "gs3", value: gs3},
    {name: "a4", value: a4},
    {name: "b4", value: b4},
    {name: "c4", value: c4}, 
    {name: "d4", value: d4},
    {name: "e4", value: e4}, 
    {name: "f4", value: f4},
    {name: "g4", value: g4}, 
    {name: "as4", value: as4},
    {name: "bs4", value: bs4},
    {name: "cs4", value: cs4}, 
    {name: "ds4", value: ds4},
    {name: "es4", value: es4}, 
    {name: "fs4", value: fs4},
    {name: "gs4", value: gs4},
    {name: "a5", value: a5},
    {name: "b5", value: b5},
    {name: "c5", value: c5}, 
    {name: "d5", value: d5},
    {name: "e5", value: e5}, 
    {name: "f5", value: f5},
    {name: "g5", value: g5}, 
    {name: "as5", value: as5},
    {name: "bs5", value: bs5},
    {name: "cs5", value: cs5}, 
    {name: "ds5", value: ds5},
    {name: "es5", value: es5}, 
    {name: "fs5", value: fs5},
    {name: "gs5", value: gs5},
    {name: "a6", value: a6},
    {name: "b6", value: b6},
    {name: "c6", value: c6}, 
    {name: "d6", value: d6},
    {name: "e6", value: e6}, 
    {name: "f6", value: f6},
    {name: "g6", value: g6}, 
    {name: "as6", value: as6},
    {name: "bs6", value: bs6},
    {name: "cs6", value: cs6}, 
    {name: "ds6", value: ds6},
    {name: "es6", value: es6}, 
    {name: "fs6", value: fs6},
    {name: "gs6", value: gs6},
    {name: "a7", value: a7},
    {name: "b7", value: b7},
    {name: "c7", value: c7}, 
    {name: "d7", value: d7},
    {name: "e7", value: e7}, 
    {name: "f7", value: f7},
    {name: "g7", value: g7}, 
    {name: "as7", value: as7},
    {name: "bs7", value: bs7},
    {name: "cs7", value: cs7}, 
    {name: "ds7", value: ds7},
    {name: "es7", value: es7}, 
    {name: "fs7", value: fs7},
    {name: "gs7", value: gs7}
]

export default pianoTunes